apiVersion: v1
kind: ServiceAccount
metadata:
  name: two-tier-sa
  namespace: default  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default  
  name: two-tier-sa
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: two-tier-sa-role-binding
  namespace: default 
subjects:
  - kind: ServiceAccount
    name: two-tier-sa  
    namespace: default
roleRef:
  kind: Role
  name: two-tier-sa
  apiGroup: rbac.authorization.k8s.io
