apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-tier-app
  labels:
    app: two-tier-app
    tier: frontend
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: two-tier-app
  template:
    metadata:
      labels:
        app: two-tier-app
        tier: frontend
    spec:
      serviceAccountName: two-tier-sa
      initContainers:
        - name: wait-for-db
          image: busybox:1.35.0-uclibc
          command:
            - "/bin/sh"
            - "-c"
            - |
              echo "Waiting for MySQL pod to be ready..."
              until nc -z -v -w30 mysql-0.mysql 3306; do
                echo "Waiting for DB..."
                sleep 5
              done
              echo "MySQL is ready!"
          envFrom:
            - configMapRef:
                name: db-config
            - secretRef:
                name: db-secret
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
      containers:
        - name: two-tier-app
          image: prakashvelusamy1999/prakash-hcl-k8s:flask_frontv1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: db-config
            - secretRef:
                name: db-secret
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
